### ISSUE TITLE
使用hexo-theme-matery报错

### ISSUE THREAD

**Issue by handbye** [PipecraftNet/hexo-filter-jsdelivr-auto-fallback#2]
你好，我使用的是hexo-theme-matery主题，当配置add_defer 为true时，首页无法显示，提示以下错误：
<img width="628" alt="image" src="https://user-images.githubusercontent.com/26617058/232974333-236dbef0-0160-4791-8c1c-de1c989ae99e.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/26617058/232974394-ea35fa26-d66c-473c-9094-6eb805078317.png">
<img width="657" alt="image" src="https://user-images.githubusercontent.com/26617058/232974440-9fa45816-dfd6-4c45-a174-cb4e4d837738.png">

**Comment by PipecraftNet** [comment]
@handbye 你好，我看了一下你的网站，发现只有图片用到 jsdelivr, JS 没有用到 jsdelivr。
这种情况建议不设置 `add_defer`，默认值为 `false`。

如果设置为 `true`，需要把 inline script 做一下处理，等到其他 JS 加载完执行。

**Comment by handbye** [comment]
好的，明白了，谢谢
