### ISSUE TITLE
插件之间冲突

### ISSUE THREAD

**Issue by paradoxsugar** [PipecraftNet/hexo-filter-jsdelivr-auto-fallback#3]
该插件会造成和[hexo-butterfly-swiper](https://github.com/Akilarlxh/hexo-butterfly-swiper)插件的冲突，导致该[issue](https://github.com/Akilarlxh/hexo-butterfly-swiper/issues/8)，使用js直接引用不会造成冲突，但仍希望作者能加以解决！

**Comment by PipecraftNet** [comment]
@paradoxsugar 看了一下你的网站，只有图片用到了 jsdelivr，JS 文件和 CSS 文件**没有**用到 jsdelivr。
这种情况 `add_defer` 设置为 `false`即可。
```yml
jsdelivr_auto_fallback:
  enable: true
  add_defer: false
```

生成的 HTML 代码里 `<script` 没有 `defer` 属性就正常了。
<img width="1049" alt="2023-12-11-14-43-36" src="https://github.com/PipecraftNet/hexo-filter-jsdelivr-auto-fallback/assets/88728670/f8281677-b220-478c-b4a2-8debdd69dd99">
